export const LEAGUE_FETCH_START = "CHARACTERS_FETCH_START";
export const LEAGUE_FETCH_FAIL = "CHARACTERS_FETCH_FAIL";

export const LEAGUE_GET_TOTAL = "LEAGUE_GET_TOTAL";
export const LEAGUE_GET_HOME = "LEAGUE_GET_HOME";
export const LEAGUE_GET_AWAY = "LEAGUE_GET_AWAY";
export const LEAGUE_GET_SCORERS = "LEAGUE_GET_SCORERS";
